networks:
  traefik_tunnel:
    name: traefik-tunnel
  traefik_apps:
    name: traefik-apps

services:
  traefik:
    container_name: traefik
    image: traefik:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./letsencrypt/:/letsencrypt
      - ./traefik.yml:/etc/traefik/traefik.yml:ro
      - ./dynamic.yml:/etc/traefik/dynamic.yml:ro
    env_file: .env
    environment:
      - TRAEFIK_CERTIFICATESRESOLVERS_CLOUDFLARE_ACME_EMAIL=${ACME_EMAIL}
    networks:
      - traefik_tunnel
      - traefik_apps
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget -qO- --timeout=5 http://127.0.0.1:8080/ping | grep -q OK || exit 1",
        ]
      interval: 30s
      timeout: 10s
      start_period: 20s
      retries: 3
    labels:
      - "traefik.enable=true"
      # Traefik Dashboard
      - "traefik.http.routers.api.rule=Host(`traefik.${DOMAIN}`)"
      - "traefik.http.routers.api.entrypoints=websecure"
      - "traefik.http.routers.api.tls=true"
      - "traefik.http.routers.api.tls.certresolver=cloudflare"
      - "traefik.http.routers.api.service=api@internal"
      - "traefik.http.routers.api.middlewares=auth"
      - "traefik.http.middlewares.auth.basicauth.users=${DASHBOARD_AUTH}"

  cloudflared:
    container_name: cfd-tunnel
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    environment:
      - TUNNEL_TOKEN=${CF_TUNNEL_TOKEN}
    command: tunnel --metrics 127.0.0.1:60123 --no-autoupdate run
    networks:
      - traefik_tunnel
    healthcheck:
      test:
        [
          "CMD",
          "cloudflared",
          "tunnel",
          "--metrics",
          "127.0.0.1:60123",
          "ready",
        ]
      interval: 30s
      timeout: 10s
      start_period: 20s
      retries: 3
