networks:
  cloudflare_tunnel:
    name: cloudflare-tunnel
    ipam:
      config:
        - subnet: 172.100.0.0/29
  traefik_apps:
    name: traefik-apps
    ipam:
      config:
        - subnet: 172.101.0.0/24

services:
  traefik:
    container_name: traefik
    image: traefik:latest
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: "0.5"
        reservations:
          memory: 256M
          cpus: "0.25"
    command:
      # API
      - --api.dashboard=true
      - --api.insecure=false
      - --ping=true
      # Entry Points
      - --entrypoints.web.address=:80
      - --entrypoints.web.http.redirections.entrypoint.to=websecure
      - --entrypoints.web.http.redirections.entrypoint.scheme=https
      - --entrypoints.websecure.address=:443
      - --entrypoints.websecure.forwardedHeaders.trustedIPs=172.100.0.0/29 # CIDR of the cloudflare_tunnel network
      - --entrypoints.websecure.http.tls.certResolver=cloudflare
      - --entrypoints.websecure.http.middlewares=crowdsec@file,compress@file
      # Providers
      - --providers.docker=true
      - --providers.docker.exposedByDefault=false
      - --providers.file.filename=/etc/traefik/dynamic.yml
      - --providers.file.watch=true
      # Certificate Resolvers
      - --certificatesresolvers.cloudflare.acme.email=${ACME_EMAIL}
      - --certificatesresolvers.cloudflare.acme.storage=/letsencrypt/acme.json
      - --certificatesresolvers.cloudflare.acme.keyType=EC384
      - --certificatesresolvers.cloudflare.acme.dnschallenge=true
      - --certificatesresolvers.cloudflare.acme.dnschallenge.provider=cloudflare
      - --certificatesresolvers.cloudflare.acme.dnschallenge.propagation.delaybeforechecks=30s
      - --certificatesresolvers.cloudflare.acme.dnschallenge.resolvers=1.1.1.1:53,8.8.8.8:53,9.9.9.9:53
      # Logging
      - --log.level=INFO
      - --log.format=json
      - --log.filePath=/var/log/traefik/traefik.log
      - --accesslog.format=json
      - --accesslog.filepath=/var/log/traefik/access.log
      # Experimental
      - --experimental.plugins.bouncer.modulename=github.com/maxlerebourg/crowdsec-bouncer-traefik-plugin
      - --experimental.plugins.bouncer.version=v1.4.5
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./data/letsencrypt/:/letsencrypt
      - ./dynamic.yml:/etc/traefik/dynamic.yml:ro
      - ./logs/traefik:/var/log/traefik
    env_file: .env
    networks:
      - cloudflare_tunnel
      - traefik_apps
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget -qO- --timeout=5 http://127.0.0.1:8080/ping | grep -q OK || exit 1",
        ]
      interval: 60s
      timeout: 15s
      retries: 3
      start_period: 30s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`traefik.${DOMAIN}`)"
      - "traefik.http.routers.api.entrypoints=websecure"
      - "traefik.http.routers.api.service=api@internal"
      - "traefik.http.routers.api.middlewares=auth@file"

  cloudflared:
    container_name: cloudflared
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: "0.25"
        reservations:
          memory: 128M
          cpus: "0.1"
    environment:
      - TUNNEL_TOKEN=${CF_TUNNEL_TOKEN}
    command: tunnel --metrics 127.0.0.1:60123 --no-autoupdate run
    networks:
      - cloudflare_tunnel
    healthcheck:
      test:
        [
          "CMD",
          "cloudflared",
          "tunnel",
          "--metrics",
          "127.0.0.1:60123",
          "ready",
        ]
      interval: 60s
      timeout: 15s
      retries: 3
      start_period: 30s

  crowdsec:
    container_name: crowdsec
    image: crowdsecurity/crowdsec:latest
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: "0.5"
        reservations:
          memory: 256M
          cpus: "0.25"
    volumes:
      - ./data/crowdsec/data:/var/lib/crowdsec/data
      - ./data/crowdsec/etc:/etc/crowdsec
      - ./acquis.yaml:/etc/crowdsec/acquis.yaml:ro
      - ./logs/traefik:/var/log/traefik:ro
    networks:
      - traefik_apps
    depends_on:
      - traefik
    environment:
      - COLLECTIONS=crowdsecurity/traefik crowdsecurity/http-cve crowdsecurity/whitelist-good-actors crowdsecurity/iptables crowdsecurity/linux
      - LOG_LEVEL=info
      - LOG_FORMAT=json
    healthcheck:
      test: ["CMD-SHELL", "cscli metrics >/dev/null 2>&1 || exit 1"]
      interval: 60s
      timeout: 15s
      retries: 3
      start_period: 30s
