networks:
  cloudflare_tunnel:
    name: cloudflare-tunnel
    ipam:
      config:
        - subnet: 172.100.0.0/29
  traefik_apps:
    name: traefik-apps
    ipam:
      config:
        - subnet: 172.101.0.0/24

services:
  traefik:
    container_name: traefik
    image: traefik:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./data/letsencrypt/:/letsencrypt
      - ./traefik.yml:/etc/traefik/traefik.yml:ro
      - ./dynamic.yml:/etc/traefik/dynamic.yml:ro
      - ./logs/traefik:/var/log/traefik
    env_file: .env
    environment:
      - TRAEFIK_CERTIFICATESRESOLVERS_CLOUDFLARE_ACME_EMAIL=${ACME_EMAIL}
    networks:
      - cloudflare_tunnel
      - traefik_apps
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget -qO- --timeout=5 http://127.0.0.1:8080/ping | grep -q OK || exit 1",
        ]
      interval: 30s
      timeout: 10s
      start_period: 20s
      retries: 3
    labels:
      - "traefik.enable=true"
      # Traefik Dashboard
      - "traefik.http.routers.api.rule=Host(`traefik.${DOMAIN}`)"
      - "traefik.http.routers.api.entrypoints=websecure"
      - "traefik.http.routers.api.tls=true"
      - "traefik.http.routers.api.tls.certresolver=cloudflare"
      - "traefik.http.routers.api.service=api@internal"
      - "traefik.http.routers.api.middlewares=auth"
      # - "traefik.http.routers.api.middlewares=auth,crowdsec@docker"
      - "traefik.http.middlewares.auth.basicauth.users=${DASHBOARD_AUTH}"
      # Crowdsec Middleware
      # - "traefik.http.middlewares.crowdsec.plugin.crowdsec-bouncer.crowdsecMode=stream"
      # - "traefik.http.middlewares.crowdsec.plugin.crowdsec-bouncer.crowdsecLapiUrl=http://crowdsec:8080"
      # - "traefik.http.middlewares.crowdsec.plugin.crowdsec-bouncer.crowdsecLapiKey=${CROWDSEC_BOUNCER_KEY}"
      # - "traefik.http.middlewares.crowdsec.plugin.crowdsec-bouncer.forwardedHeadersCustomName=CF-Connecting-IP"
      # - "traefik.http.middlewares.crowdsec.plugin.crowdsec-bouncer.forwardedHeadersTrustedIPs=172.19.0.0/24" # CIDR of the traefik_tunnel network

  cloudflared:
    container_name: cloudflared
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    environment:
      - TUNNEL_TOKEN=${CF_TUNNEL_TOKEN}
    command: tunnel --metrics 127.0.0.1:60123 --no-autoupdate run
    networks:
      - cloudflare_tunnel
    healthcheck:
      test:
        [
          "CMD",
          "cloudflared",
          "tunnel",
          "--metrics",
          "127.0.0.1:60123",
          "ready",
        ]
      interval: 30s
      timeout: 10s
      start_period: 20s
      retries: 3

  # crowdsec:
  #   container_name: crowdsec
  #   image: crowdsecurity/crowdsec:latest
  #   restart: unless-stopped
  #   volumes:
  #     - ./data/crowdsec/data:/var/lib/crowdsec/data
  #     - ./data/crowdsec/config:/etc/crowdsec
  #     - ./acquis.yaml:/etc/crowdsec/acquis.yaml
  #     - ./logs/traefik:/var/log/traefik:ro
  #   networks:
  #     - traefik_apps
  #   depends_on:
  #     - traefik
  #   environment:
  #     - COLLECTIONS=crowdsecurity/traefik
