api:
  dashboard: true
  insecure: false

ping: {}

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"
    forwardedHeaders:
      trustedIPs:
        - "172.100.0.0/29" # CIDR of the cloudflare_tunnel network
    http:
      tls:
        certResolver: cloudflare
      middlewares:
        - compress@file

providers:
  docker:
    exposedByDefault: false
  file:
    filename: /etc/traefik/dynamic.yml
    watch: true

certificatesResolvers:
  cloudflare:
    acme:
      storage: /letsencrypt/acme.json
      keyType: EC384
      dnsChallenge:
        provider: cloudflare
        delayBeforeCheck: 0s
        resolvers:
          - "1.1.1.1:53"
          - "8.8.8.8:53"

log:
  level: INFO
  format: json
  filePath: /var/log/traefik/traefik.log
accessLog:
  format: json
  filePath: /var/log/traefik/access.log
# experimental:
#   plugins:
#     crowdsec-bouncer:
#       moduleName: "github.com/maxlerebourg/crowdsec-bouncer-traefik-plugin"
#       version: "v1.4.4"
