api:
  dashboard: true
  insecure: false

ping: {}

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"
    forwardedHeaders:
      trustedIPs:
        - "172.100.0.0/29" # CIDR of the cloudflare_tunnel network
    http:
      tls:
        certResolver: cloudflare
      middlewares:
        - crowdsec@file
        - compress@file

providers:
  docker:
    exposedByDefault: false
  file:
    filename: /etc/traefik/dynamic.yml
    watch: true

certificatesResolvers:
  cloudflare:
    acme:
      email: "" # https://doc.traefik.io/traefik/getting-started/configuration-overview/#the-static-configuration
      storage: /letsencrypt/acme.json
      keyType: EC384
      dnsChallenge:
        provider: cloudflare
        propagation:
          delayBeforeChecks: 30s
        resolvers:
          - "1.1.1.1:53"
          - "8.8.8.8:53"
          - "9.9.9.9:53"

log:
  level: INFO
  format: json
  filePath: /var/log/traefik/traefik.log
accessLog:
  format: json
  filePath: /var/log/traefik/access.log

experimental:
  plugins:
    bouncer:
      moduleName: "github.com/maxlerebourg/crowdsec-bouncer-traefik-plugin"
      version: "v1.4.4"
